name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - prod



jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }} 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password:  ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            yasminemarzouk/template-fe-${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}:${{ github.sha }}
          push: true


  update-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
    needs: build-and-push
    steps:
      - name: Checkout deployment code
        uses: actions/checkout@v2
        with:
          repository: Yasminemaroukk/kustomize-
          ref: 'main'
          token: ${{ secrets.TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Deployment Image
        run: |
          IMAGE_TAG=${{ needs.build-and-push.outputs.sha }}
          LS_PATH=$([[ $GITHUB_REF == refs/heads/dev ]] && echo ${{ vars.DEV_PATH }} || echo ${{ vars.PROD_PATH }})
          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" $LS_PATH
          git add .
          git commit -m "Update image version to $IMAGE_TAG"
          git push


