name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Environment
        id: determine_environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/prod" ]; then
            echo "PROD_ENV"
          else
            echo "DEV_ENV"
          fi
        env:
          PROD_ENV: "prod"
          DEV_ENV: "dev"
      - name: Set Environment Name
        run: echo "::set-env name=ENV_NAME::${{ steps.determine_environment.outputs.stdout }}"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            yasminemarzouk/template-fe-${{ env.ENV_NAME }}:${{ github.sha }}
          push: true

  update-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Determine Environment
        id: determine_environment
        run: |
          if [ "${{ github.ref }}" = "refs/heads/prod" ]; then
            echo "PROD_ENV"
          else
            echo "DEV_ENV"
          fi
        env:
          PROD_ENV: "prod"
          DEV_ENV: "dev"
      - name: Set Environment Name
        run: echo "::set-env name=ENV_NAME::${{ steps.determine_environment.outputs.stdout }}"
      - name: Checkout deployment code
        uses: actions/checkout@v2
        with:
          repository: Yasminemaroukk/kustomize-
          ref: 'main'
          token: ${{ secrets.TOKEN }}

     
