name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
    tags:
      - 'v*.*.*'

env:
  DOCKER_IMAGE: ${{ github.ref == 'refs/heads/prod' && 'yasminemarzouk/template-fe-prod' || 'yasminemarzouk/template-fe' }}


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.short-sha.outputs.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/dev' ]]; then
            echo "DEV_VITE_API_URL=${{ secrets.DEV_VITE_API_URL }}" >> $GITHUB_ENV
            echo "DEV_PATH=dev/path" >> $GITHUB_ENV
          elif [[ ${{ github.ref }} == 'refs/heads/prod' ]]; then
            echo "PROD_VITE_API_URL=${{ secrets.PROD_VITE_API_URL }}" >> $GITHUB_ENV
            echo "PROD_PATH=prod/path" >> $GITHUB_ENV
          fi

      - name: Get short SHA
        id: short-sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Prepare Docker Tags
        id: docker-tags
        run: |
          COMMIT_SHA=${{ steps.short-sha.outputs.sha }}
          echo "COMMIT_SHA_TAG=$COMMIT_SHA" >> $GITHUB_ENV
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_TAG=${GITHUB_REF/refs\/tags\//}
            echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
            TAGS="$VERSION_TAG,$COMMIT_SHA"
          else
            TAGS="$COMMIT_SHA"
          fi
          echo "DOCKER_IMAGE_TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and Push Docker image
        run: |
          DOCKER_IMAGE=${{ env.DOCKER_IMAGE }}
          DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

          docker build -t $DOCKER_IMAGE .

          IFS=',' read -ra TAGS <<< "$DOCKER_IMAGE_TAGS"
          for TAG in "${TAGS[@]}"; do
            docker tag $DOCKER_IMAGE $DOCKER_IMAGE:$TAG
            docker push $DOCKER_IMAGE:$TAG
          done

  update-deployment:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
    needs: build-and-push
    steps:
      - name: Checkout deployment code
        uses: actions/checkout@v2
        with:
          repository: Yasminemaroukk/kustomize-
          ref: 'main'
          token: ${{ secrets.TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Deployment Image
        run: |
          IMAGE_TAG=${{ needs.build-and-push.outputs.sha }}
          LS_PATH=$([[ $GITHUB_REF == refs/heads/dev ]] && echo $DEV_PATH || echo $PROD_PATH)
          sed -i "s|newTag: .*|newTag: $IMAGE_TAG|" $LS_PATH
          git add .
          git commit -m "Update image version to $IMAGE_TAG"
          git push


