name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - prod
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract secret variables
        id: extract-secret-vars
        run: |
          python3 extract_vars.py

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password:  ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          tags: |
            yasminemarzouk/template-be-${{ github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}:${{ github.sha }}
          push: true


  update-deployment:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout deployment code
        uses: actions/checkout@v2
        with:
          repository: Yasminemaroukk/kustomize-
          ref: 'main'
          token: ${{ secrets.TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update Deployment Image
        run: |
          LS_PATH=$([[ $GITHUB_REF == refs/heads/dev ]] && echo ${{ steps.extract-secret-vars.outputs.dev_path }} || echo ${{ steps.extract-secret-vars.outputs.prod_path }})
          sed -i "s|newTag: .*|newTag: ${{ github.sha }}|" $LS_PATH
          git add .
          git commit -m "Update image version "
          git push 
